version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres_airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    networks:
      - airflow_network

  mongo_db:
    image: mongo:6
    container_name: mongodb_airflow
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - airflow_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo_express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo_db
    depends_on:
      - mongo_db
    networks:
      - airflow_network

  airflow-init:
    # GUNAKAN PYTHON 3.10 untuk compatibility yang lebih baik
    image: apache/airflow:2.9.0-python3.10
    container_name: airflow_init
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: |
      bash -c "
        # Install specific versions for compatibility
        pip install --no-cache-dir pandas==2.0.3 openpyxl==3.1.2 pymongo==4.5.0 yfinance==0.2.33
        airflow db migrate
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true
      "
    depends_on:
      - postgres
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.9.0-python3.10
    container_name: airflow_webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: |
      bash -c "
        pip install --no-cache-dir pandas==2.0.3 openpyxl==3.1.2 pymongo==4.5.0 yfinance==0.2.33
        airflow webserver
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./tickers.xlsx:/opt/airflow/tickers.xlsx
    depends_on:
      - airflow-init
    networks:
      - airflow_network

  airflow-scheduler:
    image: apache/airflow:2.9.0-python3.10
    container_name: airflow_scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres_airflow/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    command: |
      bash -c "
        pip install --no-cache-dir pandas==2.0.3 openpyxl==3.1.2 pymongo==4.5.0 yfinance==0.2.33
        airflow scheduler
      "
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./tickers.xlsx:/opt/airflow/tickers.xlsx
    depends_on:
      - airflow-webserver
    networks:
      - airflow_network

networks:
  airflow_network:
    driver: bridge